/** @module mini-dash */
module.exports = {
  .vscode: require('./.vscode'),
  chunk: require('./chunk'),
  clone: require('./clone'),
  contains: require('./contains'),
  count: require('./count'),
  countBy: require('./countBy'),
  docs: require('./docs'),
  drop: require('./drop'),
  dropRight: require('./dropRight'),
  dropWhile: require('./dropWhile'),
  extend: require('./extend'),
  fill: require('./fill'),
  find: require('./find'),
  findIndex: require('./findIndex'),
  flatMap: require('./flatMap'),
  flatten: require('./flatten'),
  groupBy: require('./groupBy'),
  head: require('./head'),
  initial: require('./initial'),
  isArray: require('./isArray'),
  isDefined: require('./isDefined'),
  isFunction: require('./isFunction'),
  isObject: require('./isObject'),
  isString: require('./isString'),
  last: require('./last'),
  omit: require('./omit'),
  tail: require('./tail'),
  take: require('./take'),
  takeRight: require('./takeRight'),
  takeRightWhile: require('./takeRightWhile'),
  takeWhile: require('./takeWhile'),
  uniqBy: require('./uniqBy'),
  zip: require('./zip'),
  zipObject: require('./zipObject'),
  zipWithIndex: require('./zipWithIndex')
}
