module.exports = {
  chunk: require('./chunk'),
  clone: require('./clone'),
  contains: require('./contains'),
  count: require('./count'),
  countBy: require('./countBy'),
  extend: require('./extend'),
  fill: require('./fill'),
  find: require('./find'),
  findIndex: require('./findIndex'),
  flatMap: require('./flatMap'),
  flatten: require('./flatten'),
  groupBy: require('./groupBy'),
  isArray: require('./isArray'),
  isDefined: require('./isDefined'),
  isFunction: require('./isFunction'),
  isObject: require('./isObject'),
  isString: require('./isString'),
  omit: require('./omit')
}